name: Build and release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
env:
  RUST_BACKTRACE: 1
  GITHUB_TOKEN: ${{ github.token }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  tag-new-version:
    name: Create new version tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      new_version: ${{ steps.create_tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT
          
      - name: Create new version tag
        id: create_tag
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"
          major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${new_version}" -m "Release ${new_version}"
          git push origin "${new_version}"

  release:
    needs: [tag-new-version]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-freebsd
            command: build
            binary-name: ansible-decryptor
            skip_tests: true

          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            command: build
            binary-name: ansible-decryptor

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            command: build
            binary-name: ansible-decryptor

          - os-name: Linux-riscv64
            runs-on: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu
            command: build
            binary-name: ansible-decryptor

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            command: build
            binary-name: ansible-decryptor.exe

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            command: build
            binary-name: ansible-decryptor

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Package Binary
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar -czf ../../../ansible-decryptor-${{ matrix.platform.os-name }}.tar.gz ${{ matrix.platform.binary-name }}
          cd -

      - name: Generate SHA256 (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd target/${{ matrix.platform.target }}/release
          $file = "${{ matrix.platform.binary-name }}"
          $hash = (Get-FileHash -Algorithm SHA256 $file).Hash.ToLower()
          "$hash  $file" | Out-File -Encoding UTF8 "../../../ansible-decryptor-${{ matrix.platform.os-name }}.sha256"
          cd ..

      - name: Generate SHA256 (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            shasum -a 256 ${{ matrix.platform.binary-name }} > ../../../ansible-decryptor-${{ matrix.platform.os-name }}.sha256
          else
            sha256sum ${{ matrix.platform.binary-name }} > ../../../ansible-decryptor-${{ matrix.platform.os-name }}.sha256
          fi
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ansible-decryptor-${{ matrix.platform.os-name }}
          path: |
            ansible-decryptor-${{ matrix.platform.os-name }}.tar.gz
            ansible-decryptor-${{ matrix.platform.os-name }}.sha256

  create-release:
    needs: [release, tag-new-version]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref == 'refs/heads/main' && needs.tag-new-version.outputs.new_version || github.ref_name }}
          files: |
            **/ansible-decryptor-*.tar.gz
            **/ansible-decryptor-*.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
