name: Release

on:
  workflow_run:
      workflows: ['Build']
      types: [completed]
      branches:
          - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Fetch auto
        run: |
          curl -L -o /tmp/auto.gz https://github.com/intuit/auto/releases/download/v11.3.0/auto-linux.gz
          gzip -d /tmp/auto.gz
          chmod +x /tmp/auto

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx /tmp/auto shipit
